---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
       TG_CHAT_ID:
         from_secret: TG_CHAT_ID
       TG_TOKEN:
         from_secret: TG_TOKEN 
       cd ~
       sudo apt install git aria2 -y
       git clone https://gitlab.com/OrangeFox/misc/scripts
       cd scripts
       sudo bash setup/android_build_env.sh
       sudo bash setup/install_android_sdk.sh
  commands:
  - bash build.sh
